# Generated by Django 4.0 on 2025-03-11 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0006_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 11, 18, 14, 57, 879119, tzinfo=utc)),
        ),
    ]
